/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_test_jnihelloworld_CompressUtil */

#ifndef _Included_com_test_jnihelloworld_CompressUtil
#define _Included_com_test_jnihelloworld_CompressUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jnihelloworld_CompressUtil
 * Method:    compressBitmap
 * Signature: (Ljava/lang/Object;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_jnihelloworld_CompressUtil_compressBitmap
  (JNIEnv *env, jclass type,
      jobject bitmap,
     jint quality,
  jbyteArray fileNameBytes_,
    jboolean optimize);

#ifdef __cplusplus
}
#endif
#endif
