/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_test_jnihelloworld_BsPatchUtils.h"
/* Header for class com_test_jnihelloworld_BsPatchUtils */


/*
 * Class:     com_test_jnihelloworld_BsPatchUtils
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_jnihelloworld_BsPatchUtils_bsdiff
  (JNIEnv *env, jobject job, jstring oldPath, jstring newPath, jstring patchPath){
        int argc = 4;
     ///__android_log_print(ANDROID_LOG_DEBUG, LOG_TGA, "hello native log");
            char * argv[argc];
            argv[0] = "bsdiff";
            argv[1] = (char*) ((*env)->GetStringUTFChars(env, oldPath, 0));
            argv[2] = (char*) ((*env)->GetStringUTFChars(env, newPath, 0));
            argv[3] = (char*) ((*env)->GetStringUTFChars(env, patchPath, 0));


            int ret = bsdiff_main(argc, argv);

            (*env)->ReleaseStringUTFChars(env, oldPath, argv[1]);
            (*env)->ReleaseStringUTFChars(env, newPath, argv[2]);
            (*env)->ReleaseStringUTFChars(env, patchPath, argv[3]);
            return ret;
  }


