/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jnihelloworld_videoc_VideoUtil */

#ifndef _Included_com_test_jnihelloworld_videoc_VideoUtil
#define _Included_com_test_jnihelloworld_videoc_VideoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jnihelloworld_videoc_VideoUtil
 * Method:    getVideoDecoderFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_jnihelloworld_videoc_VideoUtil_getVideoDecoderFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
