/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jnihelloworld_BsPatchUtils */

#ifndef _Included_com_test_jnihelloworld_BsPatchUtils
#define _Included_com_test_jnihelloworld_BsPatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jnihelloworld_BsPatchUtils
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_jnihelloworld_BsPatchUtils_bsdiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
