/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_test_jnihelloworld_videoc_VideoUtil.h"
#ifdef __cplusplus
extern "C" {
JNIEXPORT jint JNICALL Java_com_test_jnihelloworld_videoc_VideoUtil_getVideoDecoderFile
  (JNIEnv *env, jclass jcl, jstring filePath){
        int argc = 1;
        char * argv[argc];
        argv[0] = (char*) ((*env)->GetStringUTFChars(env, filePath, 0));
        int ret = videocMain(argc,argv)
        (*env)->ReleaseStringUTFChars(env, filePath, argv[0]);
        return ret;
  }
#ifdef __cplusplus
}
#endif
#endif

